[package]
name = "git-zip"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "git-zip"
path = "src/bin/git_zip.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4.20"
zip = "0.6.6"
